"""users init

Revision ID: 66bbb8a7646a
Revises: e930ff257952
Create Date: 2021-08-18 12:13:42.827462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bbb8a7646a'
down_revision = 'e930ff257952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('fromTo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'fromTo')
    # ### end Alembic commands ###
